version: '3.4'

services:
  example.api:
    image: localhost/exampleapi
    depends_on:
      - sqldata
    build:
      context: .
      dockerfile: src/Example.API/Dockerfile
    environment:
      DBConnection: 'Data Source=127.0.0.1\\desafio_backend_stefanini_sqldata_1,5434;Initial Catalog=master;Persist Security Info=True;User ID=sa;Password=Stefanini@123'

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Stefanini@123
      - ACCEPT_EULA=Y
    ports:
      - '5434:1433'
